# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy  as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__

'2.1.3'

#### 4. How to find the memory size of any array (★☆☆)

In [8]:
import sys
arr = [1,2,3,4,5]
print("Memory size of array:")

Memory size of array:


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
import numpy as np
help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
import numpy as np

# Create a null vector of size 10
vector = np.zeros(10)

# Set the fifth element to 1 (index 4 in zero-based indexing)
vector[4] = 1

print(vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
import numpy as np

# Create a vector with values from 10 to 49
vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
import numpy as np

# Create a sample vector
vector = np.arange(10)  # Example: [0, 1, 2, ..., 9]

# Reverse the vector
reversed_vector = vector[::-1]

print("Original vector:", vector)
print("Reversed vector:", reversed_vector)


Original vector: [0 1 2 3 4 5 6 7 8 9]
Reversed vector: [9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
import numpy as np

# Create a 3x3 matrix with values from 0 to 8
matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
import numpy as np

# Define the array
array = np.array([1, 2, 0, 0, 4, 0])

# Find the indices of non-zero elements
non_zero_indices = np.nonzero(array)

print("Indices of non-zero elements:", non_zero_indices[0])


Indices of non-zero elements: [0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
import numpy as np

# Create a 3x3x3 array with random values
random_array = np.random.random((3, 3, 3))

print(random_array)


[[[0.86805808 0.580091   0.49950485]
  [0.5394291  0.08742332 0.88177192]
  [0.43590538 0.53611413 0.57081814]]

 [[0.72796174 0.14973542 0.14722877]
  [0.07717372 0.62300176 0.49780831]
  [0.29777332 0.43687047 0.92952172]]

 [[0.23480998 0.06312892 0.9759961 ]
  [0.85160068 0.31366302 0.29626911]
  [0.58280011 0.98522799 0.06835941]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
import numpy as np

# Create a 10x10 array with random values
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:\n", random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
 [[0.0045945  0.03420472 0.14384169 0.47769463 0.96803989 0.07551192
  0.26806418 0.4147329  0.71883382 0.38941347]
 [0.33166084 0.98452732 0.73108623 0.03019134 0.079305   0.25935778
  0.5221438  0.7576973  0.87168604 0.63717597]
 [0.7335523  0.74331496 0.98954074 0.58953595 0.41017214 0.48375521
  0.17944202 0.52735786 0.59591634 0.00876651]
 [0.6741571  0.13104589 0.22086973 0.44106734 0.65320016 0.12545929
  0.22925632 0.46178711 0.45151024 0.89705763]
 [0.92547084 0.79520729 0.88139879 0.57602854 0.05604787 0.09481166
  0.29424033 0.5481203  0.02037147 0.61452006]
 [0.8932928  0.33030458 0.63362122 0.91446952 0.52777667 0.52042119
  0.1165426  0.00139955 0.88203592 0.38311904]
 [0.90623617 0.92365293 0.88247629 0.49472666 0.43500618 0.24175691
  0.67801947 0.36118286 0.99667087 0.15491753]
 [0.02604415 0.16726615 0.35378238 0.10691601 0.19849586 0.25728292
  0.30704064 0.45468462 0.63592832 0.26190799]
 [0.43732129 0.27198286 0.15167335 0.62555355 0.44363647 0.902363

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [1]:
import numpy as np

# Create a random vector of size 30
random_vector = np.random.rand(30)

# Find the mean value
mean_value = np.mean(random_vector)

print("Random vector:", random_vector)
print("Mean value:", mean_value)


Random vector: [0.70682455 0.86079168 0.30640495 0.99408146 0.45356521 0.9418272
 0.90877767 0.00301626 0.61773794 0.02424763 0.8837042  0.33851374
 0.55812309 0.98479723 0.77009778 0.63484637 0.85295105 0.36036707
 0.90603489 0.87756546 0.57718279 0.96190235 0.89177603 0.49500098
 0.87703039 0.70719213 0.63749834 0.66793956 0.96549943 0.66421515]
Mean value: 0.6809837523990775


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [2]:
import numpy as np

# Create a 2D array of size 5x5 filled with zeros
array_2d = np.zeros((5, 5))

# Set the borders to 1
array_2d[0, :] = 1
array_2d[-1, :] = 1
array_2d[:, 0] = 1
array_2d[:, -1] = 1

print(array_2d)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [3]:
import numpy as np

# Create an example array
original_array = np.ones((3, 3))

# Add a border of 0s around the original array
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

print("Original array:")
print(original_array)
print("Array with border:")
print(bordered_array)


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array with border:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [4]:
0 * np.nan  # nan
np.nan == np.nan  # False
np.inf > np.nan  # False
np.nan - np.nan  # nan
np.nan in set([np.nan])  # True
0.3 == 3 * 0.1  # False


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [5]:
import numpy as np

# Create a 5x5 matrix of zeros
matrix = np.zeros((5, 5))

# Assign values just below the diagonal
for i in range(1, 5):
    matrix[i, i-1] = i

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [6]:
import numpy as np

# Create an 8x8 matrix of zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [7]:
import numpy as np

# Array shape
shape = (6, 7, 8)

# Find the index of the 100th element (considering 0-based indexing)
index = np.unravel_index(100, shape)

print(index)


(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [8]:
import numpy as np

# Create a 2x2 checkerboard pattern
checkerboard_pattern = np.array([[0, 1], [1, 0]])

# Tile the 2x2 pattern to create an 8x8 matrix
checkerboard_matrix = np.tile(checkerboard_pattern, (4, 4))

print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [9]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))

print("Random matrix:")
print(random_matrix)
print("Normalized matrix:")
print(normalized_matrix)


Random matrix:
[[0.57631526 0.71059656 0.49803722 0.3497091  0.04649968]
 [0.54810868 0.42299496 0.83785899 0.20650831 0.76630498]
 [0.24771813 0.44101044 0.7700668  0.67897254 0.6360358 ]
 [0.52587239 0.16684869 0.61724172 0.82542518 0.19705846]
 [0.92712913 0.28173401 0.81609772 0.39910922 0.09121873]]
Normalized matrix:
[[0.60163282 0.75411614 0.51274408 0.34430987 0.        ]
 [0.5696028  0.42752974 0.89862917 0.18169803 0.81737592]
 [0.22849389 0.44798724 0.82164766 0.71820543 0.66944856]
 [0.54435235 0.13666249 0.64810692 0.88450994 0.17096723]
 [1.         0.26712067 0.87391813 0.40040626 0.05078078]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [10]:
import numpy as np

# Define the custom dtype
color_dtype = np.dtype([
    ('red', np.uint8),
    ('green', np.uint8),
    ('blue', np.uint8),
    ('alpha', np.uint8)
])

# Example usage
color = np.array([(255, 0, 0, 255)], dtype=color_dtype)

print(color)


[(255, 0, 0, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [11]:
import numpy as np

# Define a 5x3 matrix
matrix_5x3 = np.random.rand(5, 3)

# Define a 3x2 matrix
matrix_3x2 = np.random.rand(3, 2)

# Multiply the two matrices
result_matrix = np.dot(matrix_5x3, matrix_3x2)

print("5x3 matrix:")
print(matrix_5x3)
print("3x2 matrix:")
print(matrix_3x2)
print("Resulting 5x2 matrix after multiplication:")
print(result_matrix)


5x3 matrix:
[[0.33143143 0.69382596 0.2716002 ]
 [0.50242342 0.63934716 0.57342103]
 [0.66452782 0.63163296 0.46394543]
 [0.48003562 0.67095619 0.15365978]
 [0.04619684 0.68893738 0.57545821]]
3x2 matrix:
[[0.78986847 0.61336678]
 [0.41645649 0.2162926 ]
 [0.95371713 0.15666728]]
Resulting 5x2 matrix after multiplication:
[[0.80976532 0.39590931]
 [1.20999015 0.5362922 ]
 [1.23040992 0.61690189]
 [0.80513702 0.46363422]
 [0.87222622 0.26750313]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [12]:
import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Negate all elements which are between 3 and 8
array[(array > 3) & (array < 8)] *= -1

print(array)


[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [13]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [14]:
import numpy as np

# Create an example integer vector Z
Z = np.array([1, 2, 3, 4])

# Evaluate each expression
results = {
    "Z**Z": Z**Z,  # Legal, element-wise exponentiation
    "2 << Z >> 2": 2 << Z >> 2,  # Legal, bitwise shift operations
    "1j * Z": 1j * Z,  # Legal, complex number multiplication
    "Z / 1 / 1": Z / 1 / 1  # Legal, element-wise division
}

print("Results of legal expressions:")
for expr, result in results.items():
    print(f"{expr}: {result}")

# Explanation of illegal expressions
illegal_expressions = [
    "Z <- Z",  # Not legal, syntax error due to non-existent operator
    "Z < Z > Z"  # Not legal, chained comparison doesn't make sense in this context
]

print("\nIllegal expressions:")
for expr in illegal_expressions:
    print(f"{expr}: Not a valid Python expression")


Results of legal expressions:
Z**Z: [  1   4  27 256]
2 << Z >> 2: [1 2 4 8]
1j * Z: [0.+1.j 0.+2.j 0.+3.j 0.+4.j]
Z / 1 / 1: [1. 2. 3. 4.]

Illegal expressions:
Z <- Z: Not a valid Python expression
Z < Z > Z: Not a valid Python expression


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [15]:
result1 = np.array(0) / np.array(0)
print(result1)  # Outputs: nan with a warning


nan


C:\Users\Akhila\AppData\Local\Temp\ipykernel_5052\2885398111.py:1: RuntimeWarning: invalid value encountered in divide
  result1 = np.array(0) / np.array(0)


#### 29. How to round away from zero a float array ? (★☆☆)

In [16]:
import numpy as np

# Create a float array
float_array = np.array([-1.5, -0.2, 0.2, 1.5, 2.7, -2.7])

# Round away from zero
rounded_array = np.copysign(np.ceil(np.abs(float_array)), float_array)

print("Original array:")
print(float_array)
print("Rounded away from zero:")
print(rounded_array)


Original array:
[-1.5 -0.2  0.2  1.5  2.7 -2.7]
Rounded away from zero:
[-2. -1.  1.  2.  3. -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [17]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Find common values
common_values = np.intersect1d(array1, array2)

print("Common values:", common_values)


Common values: [4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [18]:
import numpy as np

# Ignore all warnings
np.seterr(all='ignore')

# Your code that might produce warnings
result = np.array([1, 0, -1]) / np.array([0, 0, 0])
print(result)

# Restore the original error handling
np.seterr(all='warn')


[ inf  nan -inf]


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [19]:
import numpy as np

# Calculate square root using standard numpy sqrt
standard_sqrt = np.sqrt(-1)

# Calculate square root using numpy emath sqrt
emath_sqrt = np.emath.sqrt(-1)

# Compare the results
result = (standard_sqrt == emath_sqrt)

print("np.sqrt(-1):", standard_sqrt)
print("np.emath.sqrt(-1):", emath_sqrt)
print("Are they equal?", result)


np.sqrt(-1): nan
np.emath.sqrt(-1): 1j
Are they equal? False


C:\Users\Akhila\AppData\Local\Temp\ipykernel_5052\3968573124.py:4: RuntimeWarning: invalid value encountered in sqrt
  standard_sqrt = np.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [20]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday's date:", yesterday)
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)


Yesterday's date: 2024-12-08
Today's date: 2024-12-09
Tomorrow's date: 2024-12-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [21]:
from datetime import date, timedelta

# Start and end dates for July 2016
start_date = date(2016, 7, 1)
end_date = date(2016, 7, 31)

# Generate all dates in July 2016
july_dates = [start_date + timedelta(days=i) for i in range((end_date - start_date).days + 1)]

print(july_dates)


[datetime.date(2016, 7, 1), datetime.date(2016, 7, 2), datetime.date(2016, 7, 3), datetime.date(2016, 7, 4), datetime.date(2016, 7, 5), datetime.date(2016, 7, 6), datetime.date(2016, 7, 7), datetime.date(2016, 7, 8), datetime.date(2016, 7, 9), datetime.date(2016, 7, 10), datetime.date(2016, 7, 11), datetime.date(2016, 7, 12), datetime.date(2016, 7, 13), datetime.date(2016, 7, 14), datetime.date(2016, 7, 15), datetime.date(2016, 7, 16), datetime.date(2016, 7, 17), datetime.date(2016, 7, 18), datetime.date(2016, 7, 19), datetime.date(2016, 7, 20), datetime.date(2016, 7, 21), datetime.date(2016, 7, 22), datetime.date(2016, 7, 23), datetime.date(2016, 7, 24), datetime.date(2016, 7, 25), datetime.date(2016, 7, 26), datetime.date(2016, 7, 27), datetime.date(2016, 7, 28), datetime.date(2016, 7, 29), datetime.date(2016, 7, 30), datetime.date(2016, 7, 31)]


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [24]:
import numpy as np

# Example arrays
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Perform the computation in place
np.add(A, B, out=A)    # A now contains A + B
np.divide(A, -2, out=A)  # A now contains (A + B) * (-1/2)

print(A)



UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [25]:
import numpy as np

# Create a random array of positive numbers
random_array = np.random.rand(5) * 100

# Extract the integer part using np.floor
integer_part_floor = np.floor(random_array)

print("Random array:", random_array)
print("Integer part (floor):", integer_part_floor)


Random array: [49.74708529 13.16763032 27.20219663 57.98139461 11.26043376]
Integer part (floor): [49. 13. 27. 57. 11.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [26]:
import numpy as np

# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.zeros((5, 5))
matrix += np.arange(5)

print(matrix)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [27]:
import numpy as np

# Generator function that yields 10 integers
def generate_integers():
    for i in range(10):
        yield i

# Use the generator to create an array
integer_generator = generate_integers()
integer_array = np.fromiter(integer_generator, dtype=int)

print(integer_array)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [28]:
import numpy as np

# Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [29]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(random_vector)

print("Random vector:")
print(random_vector)
print("Sorted vector:")
print(sorted_vector)


Random vector:
[0.72183182 0.26301641 0.08606814 0.25932464 0.58001122 0.43428971
 0.27571006 0.43780902 0.22766586 0.11209889]
Sorted vector:
[0.08606814 0.11209889 0.22766586 0.25932464 0.26301641 0.27571006
 0.43428971 0.43780902 0.58001122 0.72183182]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [30]:
import numpy as np

# Create a small random array
small_array = np.random.rand(10)

# Using np.sum()
np_sum_result = np.sum(small_array)

# Using Python's built-in sum()
builtin_sum_result = sum(small_array)

print("np.sum result:", np_sum_result)
print("Built-in sum result:", builtin_sum_result)


np.sum result: 5.282546043064828
Built-in sum result: 5.282546043064828


#### 4 2.Consider two random array A and B, check if they are equal (★★☆)

In [31]:
import numpy as np

# Create two random arrays
A = np.random.rand(5)
B = np.random.rand(5)

# Check if they are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are they equal?", are_equal)


Array A: [0.92063112 0.03045499 0.77051599 0.8458449  0.34798917]
Array B: [0.9586076  0.8995366  0.06006407 0.60231981 0.9864511 ]
Are they equal? False


#### 43. Make an array immutable (read-only) (★★☆)

In [32]:
import numpy as np

# Create a random array
array = np.random.rand(5)

# Make the array read-only
array.flags.writeable = False

print("Array:", array)

# Try to modify the array (this will raise an error)
try:
    array[0] = 1
except ValueError as e:
    print("Error:", e)


Array: [0.93462634 0.89418011 0.56226837 0.74624664 0.91728398]
Error: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [33]:
import numpy as np

# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.rand(10, 2) * 10  # Example values between 0 and 10

# Extract x and y coordinates

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [34]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

print("Original vector:", random_vector)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Modified vector:", random_vector)


Original vector: [0.259958   0.66926327 0.82978222 0.29339225 0.05366279 0.79186144
 0.72909437 0.42204266 0.77698715 0.59129526]
Modified vector: [0.259958   0.66926327 0.         0.29339225 0.05366279 0.79186144
 0.72909437 0.42204266 0.77698715 0.59129526]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [35]:
import numpy as np

# Define the number of points in each direction
num_points = 5

# Create a structured array
dtype = [('x', float), ('y', float)]
structured_array = np.zeros((num_points, num_points), dtype=dtype)

# Populate the structured array with coordinates
for i in range(num_points):
    for j in range(num_points):
        structured_array[i, j] = (i / (num_points - 1), j / (num_points - 1))

print(structured_array)


[[(0.  , 0.  ) (0.  , 0.25) (0.  , 0.5 ) (0.  , 0.75) (0.  , 1.  )]
 [(0.25, 0.  ) (0.25, 0.25) (0.25, 0.5 ) (0.25, 0.75) (0.25, 1.  )]
 [(0.5 , 0.  ) (0.5 , 0.25) (0.5 , 0.5 ) (0.5 , 0.75) (0.5 , 1.  )]
 [(0.75, 0.  ) (0.75, 0.25) (0.75, 0.5 ) (0.75, 0.75) (0.75, 1.  )]
 [(1.  , 0.  ) (1.  , 0.25) (1.  , 0.5 ) (1.  , 0.75) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [36]:
import numpy as np

# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix C
C = 1.0 / (X[:, np.newaxis] - Y)

print("Array X:", X)
print("Array Y:", Y)
print("Cauchy matrix C:")
print(C)


Array X: [1 2 3]
Array Y: [4 5 6]
Cauchy matrix C:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [37]:
import numpy as np

# List of numpy scalar types
scalar_types = [np.int8, np.int16, np.int32, np.int64,
                np.uint8, np.uint16, np.uint32, np.uint64,
                np.float32, np.float64]

print("Minimum and Maximum representable values for each numpy scalar type:")

for dtype in scalar_types:
    info = np.iinfo(dtype) if np.issubdtype(dtype, np.integer) else np.finfo(dtype)
    print(f"{dtype.__name__}: Min = {info.min}, Max = {info.max}")


Minimum and Maximum representable values for each numpy scalar type:
int8: Min = -128, Max = 127
int16: Min = -32768, Max = 32767
int32: Min = -2147483648, Max = 2147483647
int64: Min = -9223372036854775808, Max = 9223372036854775807
uint8: Min = 0, Max = 255
uint16: Min = 0, Max = 65535
uint32: Min = 0, Max = 4294967295
uint64: Min = 0, Max = 18446744073709551615
float32: Min = -3.4028234663852886e+38, Max = 3.4028234663852886e+38
float64: Min = -1.7976931348623157e+308, Max = 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [38]:
import numpy as np

# Create an example array
array = np.random.rand(5, 5)

# Print all the values
print(array)


[[0.62077836 0.7678414  0.79184899 0.44956665 0.66378394]
 [0.07357149 0.1807748  0.4744432  0.0755688  0.21048495]
 [0.59625387 0.01261723 0.96814784 0.13904646 0.09341578]
 [0.6675772  0.38561161 0.70762562 0.59257403 0.46407691]
 [0.33941555 0.68284735 0.01289826 0.62293712 0.00267107]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [39]:
import numpy as np

# Example vector
vector = np.array([0.1, 0.5, 0.9, 1.5, 2.0, 2.5])

# Given scalar
scalar = 1.2

# Find the closest value
closest_value = vector[np.abs(vector - scalar).argmin()]

print("Vector:", vector)
print("Given scalar:", scalar)
print("Closest value:", closest_value)


Vector: [0.1 0.5 0.9 1.5 2.  2.5]
Given scalar: 1.2
Closest value: 0.9


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [44]:
import numpy as np

# Create a random vector with shape (100, 2)
coordinates = np.random.rand(100, 2)

# Calculate point-by-point distances
distances = np.sqrt(np.sum((coordinates[:, np.newaxis, :] - coordinates[np.newaxis, :, :]) ** 2, axis=-1))

print("Coordinates:")
print(coordinates)
print("Point-by-point distances:")
print(distances)


Coordinates:
[[0.22953373 0.52143965]
 [0.60195253 0.63905729]
 [0.29512608 0.03870511]
 [0.48004276 0.67617017]
 [0.08620819 0.15535839]
 [0.88721905 0.04476779]
 [0.33579835 0.13589234]
 [0.35458003 0.86585986]
 [0.27628554 0.28203827]
 [0.97388939 0.11598148]
 [0.90492789 0.88115509]
 [0.50298034 0.72618055]
 [0.34427598 0.26166122]
 [0.37565816 0.01607134]
 [0.68793336 0.91847192]
 [0.48933599 0.06576982]
 [0.26479668 0.64990179]
 [0.68381316 0.7875415 ]
 [0.7262514  0.70543868]
 [0.92764024 0.06294951]
 [0.69960727 0.15146937]
 [0.77694038 0.82824369]
 [0.80632049 0.5708712 ]
 [0.3051574  0.61798059]
 [0.83240565 0.72041153]
 [0.15152841 0.95847677]
 [0.32795429 0.81072893]
 [0.05712904 0.33909692]
 [0.81186592 0.28165216]
 [0.93852283 0.13959411]
 [0.6470944  0.70174527]
 [0.59720182 0.84042037]
 [0.54424322 0.04340813]
 [0.73065287 0.02776408]
 [0.11320865 0.26236125]
 [0.39131263 0.36022715]
 [0.86519505 0.90183869]
 [0.66958737 0.75134506]
 [0.71089752 0.06661344]
 [0.7594612 

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [45]:
import numpy as np

# Create a float (32-bit) array
float_array = np.random.rand(10).astype(np.float32)

print("Original float array:", float_array)

# Convert to integer (32-bit) in place
float_array = float_array.astype(np.int32, copy=False)

print("Converted integer array:", float_array)


Original float array: [0.488031   0.64207035 0.710312   0.97111404 0.59573984 0.950472
 0.9654122  0.82414323 0.14779681 0.4085373 ]
Converted integer array: [0 0 0 0 0 0 0 0 0 0]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [47]:
import numpy as np

# Create a numpy array
array = np.array([[1, 2], [3, 4], [5, 6]])

# Use np.ndenumerate to iterate with index and value
for index, value in np.ndenumerate(array):
    print(f"Index: {index}, Value: {value}")


Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (1, 0), Value: 3
Index: (1, 1), Value: 4
Index: (2, 0), Value: 5
Index: (2, 1), Value: 6


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [48]:
import numpy as np

# Define the size of the array
size = 10

# Create coordinate grids for the x and y axes
x, y = np.meshgrid(np.linspace(-1, 1, size), np.linspace(-1, 1, size))

# Calculate the Gaussian-like function
sigma = 0.5
gaussian_array = np.exp(-((x**2 + y**2) / (2 * sigma**2)))

print(gaussian_array)


[[0.01831564 0.0403616  0.07300087 0.10836802 0.13203459 0.13203459
  0.10836802 0.07300087 0.0403616  0.01831564]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0.16086971 0.08894358 0.0403616 ]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [49]:
import numpy as np

# Define the size of the array
rows, cols = 5, 5
p = 10

# Create a zero 2D array
array = np.zeros((rows, cols))

# Randomly choose p unique indices to place the elements
indices = np.random.choice(rows * cols, p, replace=False)



#### 58. Subtract the mean of each row of a matrix (★★☆)

In [50]:
import numpy as np

# Create an example matrix
matrix = np.random.rand(4, 5)

# Calculate the mean of each row
row_means = matrix.mean(axis=1, keepdims=True)

# Subtract the mean of each row from the corresponding row elements
centered_matrix = matrix - row_means

print("Original matrix:")
print(matrix)
print("Row means:")
print(row_means)
print("Matrix after subtracting row means:")
print(centered_matrix)


Original matrix:
[[0.94962556 0.2149806  0.12503463 0.16637319 0.98150977]
 [0.17352858 0.29123675 0.18879839 0.37174976 0.20066296]
 [0.59725088 0.38692422 0.03878502 0.86454332 0.81838507]
 [0.73331753 0.96654876 0.46026515 0.88209871 0.47289789]]
Row means:
[[0.48750475]
 [0.24519528]
 [0.5411777 ]
 [0.70302561]]
Matrix after subtracting row means:
[[ 0.46212081 -0.27252415 -0.36247012 -0.32113156  0.49400502]
 [-0.07166671  0.04604146 -0.0563969   0.12655448 -0.04453233]
 [ 0.05607318 -0.15425348 -0.50239268  0.32336562  0.27720737]
 [ 0.03029192  0.26352315 -0.24276046  0.1790731  -0.23012772]]


#### 59. How to sort an array by the nth column? (★★☆)

In [51]:
import numpy as np

# Create an example array
array = np.array([[3, 2, 1],
                  [1, 3, 2],
                  [2, 1, 3]])

# Define the column index to sort by
n = 1

# Sort the array by the nth column
sorted_array = array[array[:, n].argsort()]

print("Original array:")
print(array)
print("Sorted array by column", n, ":")
print(sorted_array)


Original array:
[[3 2 1]
 [1 3 2]
 [2 1 3]]
Sorted array by column 1 :
[[2 1 3]
 [3 2 1]
 [1 3 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [52]:
import numpy as np

# Example 2D array with some NaN values
array = np.array([[1, np.nan, 3],
                  [4, np.nan, 6],
                  [7, np.nan, 9]])

# Check for null columns
null_columns = np.isnan(array).all(axis=0)

print("Array:")
print(array)
print("Null columns:", null_columns)


Array:
[[ 1. nan  3.]
 [ 4. nan  6.]
 [ 7. nan  9.]]
Null columns: [False  True False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [53]:
import numpy as np

# Example array
array = np.array([0.1, 0.5, 0.9, 1.5, 2.0, 2.5])

# Given value
value = 1.2

# Find the nearest value
nearest_value = array[np.abs(array - value).argmin()]

print("Array:", array)
print("Given value:", value)
print("Nearest value:", nearest_value)


Array: [0.1 0.5 0.9 1.5 2.  2.5]
Given value: 1.2
Nearest value: 0.9


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [54]:



import numpy as np

# Define two arrays with shapes (1, 3) and (3, 1)
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

# Create a result array with the broadcasted shape
result = np.empty((3, 3))

# Use nditer to iterate and compute the sum
with np.nditer([array1, array2, result], flags=['multi_index'], op_flags=[['readonly'], ['readonly'], ['writeonly']]) as it:
    for x, y, res in it:
        res[...] = x + y

print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("Resulting sum array:")
print(result)


Array 1:
[[1 2 3]]
Array 2:
[[4]
 [5]
 [6]]
Resulting sum array:
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [55]:
import numpy as np

class NamedArray:
    def __init__(self, array, name):
        self.array = np.array(array)
        self.name = name

    def __repr__(self):
        return f"NamedArray(name={self.name}, array={self.array})"

    def __getitem__(self, index):
        return self.array[index]

    def __setitem__(self, index, value):
        self.array[index] = value

    # You can add more methods as needed to handle array operations

# Example usage
array = NamedArray([1, 2, 3, 4, 5], "MyArray")

print(array)  # Output: NamedArray(name=MyArray, array=[1 2 3 4 5])
print("Name of the array:", array.name)  # Output: MyArray

NamedArray(name=MyArray, array=[1 2 3 4 5])
Name of the array: MyArray


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [56]:
import numpy as np

# Example given vector
vector = np.array([0, 1, 2, 3, 4])

# Example indices vector
indices = np.array([0, 1, 2, 1, 3, 3, 4])

# Add 1 to each element indexed by the second vector
np.add.at(vector, indices, 1)

print("Modified vector:", vector)


Modified vector: [1 3 3 5 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [57]:
import numpy as np

# Example vector X
X = np.array([1, 2, 3, 4, 5])

# Example index list I
I = np.array([0, 1, 2, 1, 3])

# Initialize the array F with zeros, with the same shape as needed
F = np

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [58]:
import numpy as np

# Create an example image with shape (w, h, 3) and dtype=ubyte
w, h = 4, 4  # example dimensions
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

# Reshape the image to a 2D array where each row is a color (R, G, B)
reshaped_image = image.reshape(-1, 3)

# Use np.unique to find unique colors
unique_colors = np.unique(reshaped_image, axis=0)

# Count the number of unique colors
num_unique_colors = unique_colors.shape[0]

print("Image:")
print(image)
print("Number of unique colors:", num_unique_colors)


Image:
[[[  5 251 231]
  [ 48 160 104]
  [116  63  69]
  [ 14 125 214]]

 [[156  87 245]
  [150  50  42]
  [175  45  53]
  [208 146  74]]

 [[155  10  97]
  [  9  87 211]
  [128  20   2]
  [  2 230 140]]

 [[125  68 210]
  [124  43 219]
  [ 13 144 120]
  [ 69  79 163]]]
Number of unique colors: 16


#### 67.Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [59]:
import numpy as np

# Create a 4D array
array = np.random.rand(3, 4, 5, 6)

# Sum over the last two axes (axis=-2 and axis=-1)
sum_over_last_two_axes = np.sum(array, axis=(-2, -1))

print("Original array shape:", array.shape)
print("Sum over the last two axes shape:", sum_over_last_two_axes.shape)
print("Sum over the last two axes:")
print(sum_over_last_two_axes)


Original array shape: (3, 4, 5, 6)
Sum over the last two axes shape: (3, 4)
Sum over the last two axes:
[[14.36717804 15.63632319 13.1489061  12.75375478]
 [13.71572706 12.86510073 17.41551538 15.31126029]
 [18.30557084 14.71088596 12.92395533 13.34334296]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [60]:
import numpy as np

# Example vector D
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Example vector S describing subset indices
S = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

# Compute the sum and count for each subset
sum_per_subset = np.bincount(S, weights=D)
count_per_subset = np.bincount(S)

# Compute the means of subsets
mean_per_subset = sum_per_subset / count_per_subset

print("Vector D:", D)
print("Subset indices S:", S)
print("Means of subsets:", mean_per_subset)


Vector D: [ 1  2  3  4  5  6  7  8  9 10]
Subset indices S: [0 1 0 1 0 1 0 1 0 1]
Means of subsets: [5. 6.]


(★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [61]:
import numpy as np

# Original vector
original_vector = np.array([1, 2, 3, 4, 5])

# Create a new vector with space for 3 zeros between each element
new_vector = np.zeros(len(original_vector) * 4 - 3, dtype=original_vector.dtype)

# Assign the original values to the appropriate positions
new_vector[::4] = original_vector

print("Original vector:", original_vector)
print("New vector with zeros interleaved:", new_vector)


Original vector: [1 2 3 4 5]
New vector with zeros interleaved: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [62]:
import numpy as np

# Create an example 3D array of shape (5, 5, 3)
array_3d = np.random.rand(5, 5, 3)

# Create an example 2D array of shape (5, 5)
array_2d = np.random.rand(5, 5)

# Multiply the 3D array by the 2D array using broadcasting
result = array_3d * array_2d[:, :, np.newaxis]

print("3D Array:")
print(array_3d)
print("2D Array:")


3D Array:
[[[0.84135211 0.8686938  0.33664891]
  [0.0743713  0.34911287 0.48307802]
  [0.41871534 0.42874033 0.99191286]
  [0.63677643 0.2314116  0.07507054]
  [0.17127531 0.49543127 0.51492528]]

 [[0.46025808 0.15427734 0.90966511]
  [0.65376187 0.98223668 0.64437941]
  [0.51040978 0.92838177 0.63160122]
  [0.44842631 0.96894661 0.05515638]
  [0.28783778 0.11952071 0.47412687]]

 [[0.14557933 0.97003607 0.68540391]
  [0.83171271 0.34406295 0.43282186]
  [0.32777517 0.49286424 0.90180415]
  [0.49938762 0.80538948 0.81152771]
  [0.64921782 0.44694264 0.96989229]]

 [[0.62070629 0.63464883 0.48181106]
  [0.2794426  0.80316833 0.10265526]
  [0.90501464 0.25584358 0.07763668]
  [0.15524885 0.03268069 0.559941  ]
  [0.61711289 0.52312382 0.74752902]]

 [[0.7115335  0.81098866 0.87302355]
  [0.52133178 0.15759839 0.18690314]
  [0.21510152 0.89092357 0.54067054]
  [0.93499212 0.37664137 0.25043366]
  [0.00598107 0.299187   0.399975  ]]]
2D Array:


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [116]:
import numpy as np

# Example triplets describing triangles (with shared vertices)
triangles = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5],
    [4, 5, 6],
    [5, 6, 7],
    [6, 7, 8],
    [7, 8, 9],
    [8, 9, 10],
    [9, 10, 11]
])

# Example vertex coordinates
vertices = np.array([
    [0, 0],
    [1, 0],
    [1, 1],
    [0, 1],
    [2, 0],
    [2, 1],
    [3, 0],
    [3, 1],
    [4, 0],
    [4, 1],
    [5, 0],
    [5, 1]
])

# Function to compute the area of a triangle given

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [64]:
import numpy as np

# Example bincount array C
C = np.array([0, 2, 1, 0, 3])

# Initialize an empty list to store the values
A = []

# Iterate over the elements of C
for value, count in enumerate(C):
    A.extend([value] * count)

# Convert the list to a numpy array
A = np.array(A)

print("Bincount array C:", C)
print("Resulting array A:", A)
print("Bincount of A:", np.bincount(A))


Bincount array C: [0 2 1 0 3]
Resulting array A: [1 1 2 4 4 4]
Bincount of A: [0 2 1 0 3]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [65]:
import numpy as np

# Example array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define the window size
window_size = 3

# Create the window (all elements are 1)
window = np.ones(window_size)

# Compute the sliding window averages using convolution
averages = np.convolve(array, window, mode='valid') / window_size

print("Original array:", array)
print("Sliding window averages:", averages)


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Sliding window averages: [2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [66]:
import numpy as np

# Example one-dimensional array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Define the size of the subarrays
subarray_size = 3

# Initialize the two-dimensional

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [67]:
import numpy as np

# Create a boolean array
bool_array = np.array([True, False, True, False])

# Negate the boolean values in place
np.logical_not(bool_array, out=bool_array)

print("Negated boolean array:", bool_array)


Negated boolean array: [False  True False  True]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [114]:
import numpy as np

def point_to_line_distance(p, P0, P1):
    # Vector from P0 to P1
    line_vec = P1 - P0
    # Vector from P0 to p
    p_vec = p - P0
    # Line segment length squared
    line_len_sq = np.sum(line_vec**2, axis=1)
    # Projection of p_vec onto line_vec normalized
    t = np.clip(np.sum(p_vec * line_vec, axis=1) / line_len_sq, 0, 1)
    # Projection point on the line
    projection = P0 + t[:, np.newaxis] * line_vec
    # Distance from p to the projection
    distance = np.sqrt(np.sum((projection)))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [69]:
import numpy as np

# Example sets of points P0, P1, and P
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
P = np.array([[1, 1], [2, 2], [3, 3]])

# Number of lines and points
num_lines = P0.shape[0]
num_points = P.shape[0]

# Initialize the distance matrix
distances = np.zeros((num_points, num_lines))

# Compute distances
for i in range(num_lines

SyntaxError: incomplete input (3842845797.py, line 16)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [72]:
import numpy as np

def extract_subpart(array, center, shape, fill_value=0):
    """
    Extract a subpart of the array with the specified shape centered on the given element.
    Pads with fill_value if necessary.

    Parameters:
    - array: Input numpy array
    - center: Tuple indicating the center (row, col)
    - shape: Tuple indicating the desired shape (height, width)
    - fill_value: Value used for padding when necessary

    Returns:
    - subpart: Extracted subpart of the array with padding if needed
    """
    center_row, center_col = center
    height, width = shape
    
    # Calculate the start and end indices for the subpart
    start_row = center_row - height // 2
    end_row = start_row + height
    start_col = center_col - width // 2
    end_col = start_col + width
    
    # Initialize the output array with the fill value
    subpart = np.full((height, width), fill_value, dtype=array.dtype)
    
    # Calculate the range of the original array to copy into the subpart
    array_start_row = max(start_row, 0)
    array_end_row = min(end_row, array.shape[0])
    array_start_col = max(start_col, 0)
    array_end_col = min(end_col, array.shape[1])
    
    # Calculate the

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [73]:
import numpy as np

# Define the original array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Generate the new array R
R = np.array

#### 82. Compute a matrix rank (★★★)

In [74]:
import numpy as np

# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Matrix:")
print(matrix)
print("Rank of the matrix:", rank)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of the matrix: 2


#### 83. How to find the most frequent value in an array?

In [75]:
import numpy as np

# Example array
array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Find the most frequent value
most_frequent_value = np.bincount(array).argmax()

print("Array:", array)
print("Most frequent value:", most_frequent_value)


Array: [1 2 2 3 3 3 4 4 4 4]
Most frequent value: 4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [78]:
import numpy as np

# Create a random 10x10 matrix
matrix = np.random.rand(10, 10)

# Initialize a list to hold the 3x3 blocks
blocks = []

# Iterate over possible starting points for 3x3 blocks
for i in range(matrix.shape[0] - 2):
    for j in range(matrix.shape[1] - 2):
        # Extract the 3x3 block
        block = matrix[i:i+3, j:j+3]
        blocks.append(block)  # Corrected line

print("Original 10x10 matrix:")
print(matrix)

print("\nList of 3x3 blocks:")
for b in blocks:
    print(b)


Original 10x10 matrix:
[[0.2981124  0.10879311 0.6246195  0.62555059 0.51529923 0.48985344
  0.3765683  0.2119594  0.83544512 0.79465084]
 [0.25330601 0.45242204 0.73979929 0.6259486  0.67242213 0.66009074
  0.26361077 0.94734642 0.25969209 0.70881346]
 [0.42202834 0.37800341 0.07701174 0.82141115 0.17208376 0.77252293
  0.68831431 0.13866802 0.60112293 0.53045822]
 [0.79486768 0.6179101  0.38770167 0.32271631 0.16695586 0.08203803
  0.72159472 0.97776408 0.69594686 0.94378991]
 [0.90580576 0.02992756 0.73050772 0.15007262 0.26102218 0.11483329
  0.09703156 0.87778661 0.36859861 0.68459227]
 [0.67751192 0.91419502 0.6747714  0.65163824 0.8136652  0.96028797
  0.01040349 0.09744494 0.07372789 0.07664247]
 [0.16316939 0.41066767 0.54454474 0.9188399  0.36313705 0.27130655
  0.77877721 0.86214256 0.47099828 0.0568707 ]
 [0.95333172 0.17361183 0.95823097 0.64600903 0.10725447 0.51711989
  0.90236507 0.20583309 0.02986347 0.10708004]
 [0.463593   0.93308711 0.41685243 0.76881802 0.41895896 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [80]:
import numpy as np

class SymmetricArray(np.ndarray):
    def __new__(cls, shape, *args, **kwargs):
        # Ensure the shape is a square matrix
        if shape[0] != shape[1]:
            raise ValueError("Shape must be a square matrix")
        
        # Create the array instance
        obj = super().__new__(cls, shape, *args, **kwargs)
        return obj

    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

# Example usage
shape = (4,)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [81]:
import numpy as np

# Example matrices (p, n, n) and vectors (p, n, 1)
p = 3
n = 4
matrices = np.random.rand(p, n, n)
vectors = np.random.rand(p, n, 1)

# Compute the matrix products
products = np.matmul(matrices, vectors)

# Sum the results across the first axis
result = np.sum(products, axis=0)

print("Matrices:")
print(matrices)
print("Vectors:")
print(vectors)
print("Sum of matrix products (result):")
print(result)



Matrices:
[[[0.53687973 0.82934933 0.9034308  0.85384126]
  [0.30927087 0.29736978 0.27018676 0.52237183]
  [0.30215617 0.60068442 0.00400801 0.83184022]
  [0.64221914 0.73661729 0.75152953 0.80321009]]

 [[0.30476363 0.6500167  0.60625086 0.96366789]
  [0.83329283 0.24236634 0.94316551 0.78763534]
  [0.97101291 0.73840935 0.96177323 0.98441058]
  [0.6787396  0.95604312 0.08322718 0.60342702]]

 [[0.85762293 0.13160406 0.02381009 0.23736793]
  [0.5142502  0.80296819 0.3146201  0.43778804]
  [0.7232963  0.71551109 0.38290318 0.67089924]
  [0.25434805 0.72572459 0.84582116 0.58678551]]]
Vectors:
[[[0.11435727]
  [0.6696516 ]
  [0.01011294]
  [0.5708627 ]]

 [[0.95414534]
  [0.63659212]
  [0.32394069]
  [0.45938779]]

 [[0.03159481]
  [0.43558574]
  [0.60834929]
  [0.86984598]]]
Sum of matrix products (result):
[[2.76238426]
 [3.09038344]
 [4.22308356]
 [3.94235473]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [82]:
import numpy as np

# Create a 16x16 array
array = np.random.rand(16, 16)

# Reshape the array to create blocks and sum them
block_size = 4
block_sum = array.reshape(16//block_size, block_size, 16//block_size, block_size).sum(axis=(1, 3))

print("Original array:")
print(array)
print("\nBlock sum:")
print(block_sum)


Original array:
[[3.15818636e-02 3.23303918e-01 4.20437619e-01 6.31619236e-01
  4.65372011e-01 8.53286584e-01 1.34282716e-01 4.34777088e-01
  4.09715512e-01 2.29057760e-01 2.91609528e-01 8.18431369e-01
  6.40710327e-01 9.40713047e-01 4.52125074e-01 4.97239822e-01]
 [9.98259232e-01 1.12630604e-01 7.94308005e-01 7.89845733e-01
  9.02941580e-01 1.10204287e-01 4.64457683e-01 2.50392558e-01
  7.59515322e-01 6.78075158e-01 5.26324825e-01 4.66482719e-01
  2.59877542e-01 5.39019198e-01 6.53421372e-01 1.20303968e-01]
 [5.90511997e-01 3.72680405e-01 4.99928995e-01 7.31171074e-01
  9.18451608e-01 1.94953167e-02 2.78356864e-01 2.95366747e-01
  1.06210501e-01 6.32518551e-01 2.06838916e-01 6.38517916e-02
  4.81180520e-01 6.43958139e-01 9.62581611e-01 5.10904726e-01]
 [7.28359753e-01 2.10277657e-01 3.34626602e-01 1.42592824e-01
  7.20515295e-01 5.69696250e-02 7.92251485e-01 3.58058279e-01
  7.49844793e-01 6.31982614e-01 6.73895883e-01 2.94169357e-01
  3.95575476e-01 4.88945354e-01 5.87154250e-01 5.34

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [83]:
import numpy as np

def initialize_grid(size):
    """ Initialize the game grid with random 0s and 1s. """
    return np.random.randint(2, size=(size, size))

def count_neighbors(grid):
    """ Count the number of live neighbors for each cell. """
    neighbors = np.zeros(grid.shape, dtype=int)
    for i in range(-1, 2):
        for j in range(-1, 2):
            if i == 0 and j == 0:
                continue
            neighbors += np.roll(np.roll(grid, i, axis=0), j, axis=1)
    return neighbors

def update_grid(grid):
    """ Update the grid

SyntaxError: incomplete input (266786260.py, line 18)

#### 89. How to get the n largest values of an array (★★★)

In [84]:
import numpy as np

# Example array
array = np.array([1, 3, 5, 7, 2, 8, 6, 4, 10, 9])

# Number of largest values to get
n = 3

# Get the indices of the n largest values
largest_indices = np.argsort(array)[-n:]

# Get the n largest values
largest_values = array[largest_indices]

print("Original array:", array)
print(f"The {n} largest values:", largest_values)


Original array: [ 1  3  5  7  2  8  6  4 10  9]
The 3 largest values: [ 8  9 10]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [85]:
import itertools
import numpy as np

# Example vectors
vectors = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7, 8])]

# Compute the Cartesian product
cartesian_product = list(itertools.product(*vectors))

# Convert the result to a numpy array (optional)
cartesian_product_array = np.array(cartesian_product)

print("Vectors:")
for v in vectors:
    print(v)
print("\nCartesian product:")
print(cartesian_product_array)


Vectors:
[1 2 3]
[4 5]
[6 7 8]

Cartesian product:
[[1 4 6]
 [1 4 7]
 [1 4 8]
 [1 5 6]
 [1 5 7]
 [1 5 8]
 [2 4 6]
 [2 4 7]
 [2 4 8]
 [2 5 6]
 [2 5 7]
 [2 5 8]
 [3 4 6]
 [3 4 7]
 [3 4 8]
 [3 5 6]
 [3 5 7]
 [3 5 8]]


#### 91. How to create a record array from a regular array? (★★★)

In [93]:
import numpy as np

# Regular array
regular_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Define the data type for the fields
dtype = [('field1', 'i4'), ('field2', 'i4'), ('field3', 'i4')]

# Convert the regular array to a record array
record_array = np.core.records.fromarrays(regular_array.T, dtype=dtype)

print("Record array:")
print(record_array)


Record array:
[(1, 2, 3) (4, 5, 6) (7, 8, 9)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [94]:
import numpy as np

# Create a large vector Z
Z = np.random.rand(1000000)

# Method 1: Element-wise power using **
Z_power3_method1 = Z ** 3

print("Method 1 result:", Z_power3_method1)


Method 1 result: [9.13982064e-03 9.31547900e-01 3.58098704e-01 ... 2.87972504e-05
 5.51512882e-01 5.10787629e-02]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [95]:
import numpy as np

# Example arrays
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9],
    [1, 2, 4],
    [3, 5, 7]
])
B = np.array([
    [1, 2],
    [5, 6]
])

#

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [110]:
import numpy as np

# Create an example 10x3 matrix
matrix = np.array([
    [1, 2, 3],
    [2, 2, 3],
    [3, 3, 3],
    [4, 5, 4],
    [5, 5, 5],
    [6, 6, 6],
    [7, 8, 9],
    [8, 8, 8],
    [9, 1, 1],
    [0, 0, 0]
])

# Extract rows with unequal values
unequal_rows = np.array([row for row in matrix if len(np.unique(row)) > 1])

print("Original matrix:")
print(matrix)
print("\nRows with unequal values:")
print(unequal_rows)


Original matrix:
[[1 2 3]
 [2 2 3]
 [3 3 3]
 [4 5 4]
 [5 5 5]
 [6 6 6]
 [7 8 9]
 [8 8 8]
 [9 1 1]
 [0 0 0]]

Rows with unequal values:
[[1 2 3]
 [2 2 3]
 [4 5 4]
 [7 8 9]
 [9 1 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [108]:
import numpy as np

# Example vector of integers
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Determine the number of bits needed for the binary representation
num_bits = np.ceil(np.log2(np.max(vector) + 1)).astype(int)

# Function to convert an integer to binary representation with padding
def int_to_binary_array(x, num_bits):
    return np.array(list(np.binary_repr(x).zfill(num_bits))).astype(int)

# Convert the vector into a matrix of binary representations
binary_matrix = np.array([int_to_binary_array(x, num_bits) for x in vector])

print("Original vector:")
print(vector)
print("\nBinary representation matrix:")
print(binary_matrix)


Original vector:
[ 1  2  3  4  5  6  7  8  9 10]

Binary representation matrix:
[[0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [98]:
import numpy as np

# Example two-dimensional array
array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])

# Extract unique rows
unique_rows = np.unique(array, axis=0)

print("Original array:")
print(array)
print("\nUnique rows:")
print(unique_rows)


Original array:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]

Unique rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [99]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

inner_product = np.einsum('i,i', A, B)
print("Inner product:", inner_product)


Inner product: 32


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [100]:
import numpy as np
from scipy.interpolate import interp1d

def sample_path_equidistant(X, Y, num_samples):
    # Compute the distances between each consecutive points
    distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
    
    # Compute the cumulative distances along the path
    cumulative_distances = np.concatenate(([0], np.cumsum(distances)))

    # Create the interpolation function for X and Y
    interp_func_X = interp1d(cumulative_distances, X, kind='linear')
    interp_func_Y = interp1d(cumulative_distances, Y, kind='linear')

    # Define the new equidistant points
    equidistant_points = np

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [101]:
import numpy as np

def select_multinomial_rows(X, n):
    # Check if each element is an integer and if the row sums to n
    is_integer = np.all(np.mod(X, 1) == 0, axis=1)
    sums_to_n = np.sum(X, axis=1) == n
    valid_rows = np.where(is_integer & sums_to_n)[0]
    return X[valid_rows]



#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [106]:
import numpy as np

def bootstrap_confidence_interval(data, num_samples=1000, confidence_level=95):
    """
    Compute bootstrapped confidence intervals for the mean of a 1D array.

    Parameters:
    - data: 1D numpy array
    - num_samples: Number of bootstrap samples
    - confidence_level: Confidence level for the interval (default is 95)

    Returns:
    - Tuple containing the lower and upper confidence intervals
    """
    # Create an array to store the means of the bootstrap samples
    bootstrapped_means = np.empty(num_samples)
    
    # Perform the bootstrap sampling
    for i in range(num_samples):
        # Resample with replacement from the data
        sample = np.random.choice(data, size=len(data), replace=True)
        # Compute the mean of the resampled data
        bootstrapped_means[i] = np.mean(sample)
    
    # Compute the confidence interval
    alpha = (100 - confidence_level) / 100
    lower